apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-25T20:26:19Z"
  labels:
    app: mypod
  name: mypod
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - java -jar /app.jar
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
    - name: TERM
      value: xterm
    - name: LANG
      value: C.UTF-8
    - name: JAVA_HOME
      value: /usr/lib/jvm/java-1.8-openjdk/jre
    - name: JAVA_VERSION
      value: 8u212
    - name: JAVA_ALPINE_VERSION
      value: 8.212.04-r0
    - name: container
      value: podman
    - name: HOSTNAME
      value: mypodd
    image: localhost:5000/hellopodman
    name: hellopodmancontainer
    ports:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    stdin: true
    tty: true
    workingDir: /
status: {}


